# -- general -------------------------------------------------------------------

set -g default-terminal "tmux-256color"
set -as terminal-features ',*256col*:RGB'
set -as terminal-features ',xterm-ghostty:hyperlinks'
set -s extended-keys always   # pass modified keys such as Shift+Enter to applications
set -s extended-keys-format csi-u
set -s escape-time 0
set -s focus-events on
set -g repeat-time 600
set -g history-limit 100000
set -g default-shell "${SHELL}"
setw -g mouse on

set -g prefix C-l
set -gu prefix2
unbind C-b
bind C-l send-prefix

setw -g status-keys vi
setw -g mode-keys vi

# -- display -------------------------------------------------------------------

set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on
set -g set-titles-string "#h ❐ #S ● #I #W"
set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 10
setw -g monitor-activity on
set -g visual-activity off

# -- navigation ----------------------------------------------------------------

bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -h -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r p previous-window
bind -r n next-window

# -- copy mode -----------------------------------------------------------------

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line

# -- theme ---------------------------------------------------------------------

set -g status-style "fg=#8a8a8a,bg=#080808"
set -g status-left "#[fg=#080808,bg=#ffff00,bold] ❐ #S #[default] "
set -g status-left-length 100
set -g status-right " #{?client_prefix,⌨ ,}#{?session_many_attached,⚇ ,}#{?pane_synchronized,⚏ ,}"

setw -g window-status-format " #I #W#{?#{||:#{window_bell_flag},#{window_zoomed_flag}}, ,}#{?window_bell_flag,!,}#{?window_zoomed_flag,Z,} "
setw -g window-status-current-format "#{E:window-status-format}"
setw -g window-status-current-style "fg=#080808,bg=#00afff,bold"
setw -g window-status-last-style "fg=#00afff,bg=#303030"
setw -g window-status-activity-style "underscore"
setw -g window-status-bell-style "fg=#ffff00,blink,bold"

setw -g pane-border-style "fg=#303030"
setw -g pane-active-border-style "fg=#{?pane_in_mode,#ffff00,#{?synchronize-panes,#d70000,#00afff}}"
set -g message-style "fg=#080808,bg=#ffff00,bold"
set -g message-command-style "fg=#ffff00,bg=#080808,bold"
setw -g mode-style "fg=#080808,bg=#ffff00,bold"
